# este recurso requiere adaptaciones

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-parametricas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-parametricas-pod
  template:
    metadata:
      labels:
        app: ms-parametricas-pod
    spec:
      containers:
      - name: ms-parametricas-container
        image: stelios.trebolit.local:8089/nexus/repository/trebol-develop/ms-parametricas
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: ms-parametricas
spec:
  selector:
    app: ms-parametricas-pod
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: ms-parametricas
spec:
  rules:
  - host: stelios.trebolit.local
    http:
      paths:
      - backend:
          serviceName: ms-parametricas
          servicePort: 80
        path: /ms-parametricas/?(.*)
